console.log(typeof (5 > 3))
console.log(typeof (5 < 3))
console.log(typeof (5 >= 5))
console.log(typeof (3 <= 5))
console.log(typeof (5 == 5))
console.log(typeof ("Gildevan" != "gildevan"))
console.log(typeof (5 === 5))
console.log(typeof (5 === '5'))